### ISSUE TITLE
Match Time footonsat 1.4

### ISSUE THREAD

**Issue by fjr7** [zKhadiri/FootOnsat#16]
Hi friend, first tks for this plugin i really love. Great job. Just have One problem how to fix the Match Time cause is +1 Hour that the enigma time. Can you Help please. Tks in advance

**Comment by Gustus26** [comment]
I waited for a fix and this time nothing so i fixed mine myself 


So in  interface.py you will see  below

def getTime(self, match_date):
		timezone = strftime("%z")
		if timezone.startswith('+') and timezone != '+0000':
			dif = int(timezone.replace('+', '').replace('00', ''))
			calc = (datetime.strptime(match_date, '%H:%M - %Y-%m-%d') + timedelta(hours=dif)).strftime('%H:%M - %Y-%m-%d')
		elif timezone == '+0000':
			calc = match_date
		else:
			dif = int(timezone.replace('-', '').replace('00', ''))
			calc = (datetime.strptime(match_date, '%H:%M - %Y-%m-%d') - timedelta(hours=dif)).strftime('%H:%M - %Y-%m-%d')
		return calc

You change  the (hours=dif)) to (hours=-0))

So mine is like this

	def getTime(self, match_date):
		timezone = strftime("%z")
		if timezone.startswith('+') and timezone != '+0000':
			dif = int(timezone.replace('+', '').replace('00', ''))
			calc = (datetime.strptime(match_date, '%H:%M - %Y-%m-%d') + timedelta(hours=-0)).strftime('%H:%M - %Y-%m-%d')
		elif timezone == '+0000':
			calc = match_date
		else:
			dif = int(timezone.replace('-', '').replace('00', ''))
			calc = (datetime.strptime(match_date, '%H:%M - %Y-%m-%d') - timedeltaSave hours=-0)).strftime('%H:%M - %Y-%m-%d')
		return calc
Save file and reboot box and now time is correct.

**Comment by fjr7** [comment]
Many tks Gustus26...great job. Its perfect now. Tks once again.

**Comment by fjr7** [comment]
Hi, the time since today is not correct again on the Footonsat. I try to change the Deltatime in the file interface.py but with no sucess. Anyone can help? Tks in advance

**Comment by zKhadiri** [comment]
fixed.
