### ISSUE TITLE
Error API on Footonsat 

### ISSUE THREAD

**Issue by fjr7** [zKhadiri/FootOnsat#17]
Friends, recently show up and error on plugin Footonsat: "An unexpected http error occurred during the API request". 
Can anyone solve that please. Tks

**Comment by zKhadiri** [comment]
We were upgrading the server.

**Comment by fjr7** [comment]
Dar Friend Zkhadiri,
Are you upgrading the server again? Cause a get the same error again on plugin Footonsat: "An unexpected http error occurred during the API request"
Tks

**Comment by fjr7** [comment]
Its on again...many tks Zkhadiri cause its a great plugin!!
