### ISSUE TITLE
API problem 

### ISSUE THREAD

**Issue by fjr7** [zKhadiri/FootOnsat#18]
Dear Zkhadiri,

the API problem hás return to this great plugin. Can you please fix that please? Tks on advanced.

**Comment by zKhadiri** [comment]
Fixed
https://github.com/zKhadiri/FootOnsat/commit/11efadc4cc46fb392999d9064983a996e586247c

**Comment by fjr7** [comment]
Many tks but still this error:
Error in sintex file launcher.py - line66
